### ISSUE TITLE
CAPTCHA during sign in broken

### ISSUE THREAD

**Issue by DavidCo23** [croberts22/myanilist-bugs#103]
When attempting to sign into an anilist account from within the app, the captcha is not displaying the selectable image tiles after checking the CAPTCHA box. Signing in using Safari everything works normally, so it appears to be an issue with the app, not the site.

I've tried turning off content blockers as well as attempted requesting the desktop version of the site but the issue persists. 

https://github.com/croberts22/myanilist-bugs/assets/3335276/12f74fff-ca9a-45c1-82d9-c9eaa4775b91

**Comment by croberts22** [comment]
Unfortunately I don't (nor can't) control this website at all; I'm not doing any kind of adjustments here. Sometimes this happens, sometimes it doesn't. I'd suggest talking with the web developer over at AniList.co to see what the issue could be.
