### ISSUE TITLE
Next episode countdown pushed over score

### ISSUE THREAD

**Issue by thesaderic** [croberts22/myanilist-bugs#12]
## Describe the issue
 Anime with long titles make the next episode countdown get pushed over anime score.

## How can you reproduce it?

1. Go to Anime List
2. See visual bug

## What's the expected behavior?
 Either making the countdown push the score or create a new line.

## How reproducible is this issue?
 Restarted the app and refreshed my list, no change was noticed.

## Device Information

iOS Version: 15.2

MyAniList Version: 2.10.0

iOS Device: iPhone XS

Jailbroken: No

### Screenshots

![DD9A0E01-DD31-415C-8B70-087E8BB8F15A](https://user-images.githubusercontent.com/23202660/146379899-fb4cc61e-8a67-47fc-9dfc-b406cd2ae694.png)

**Comment by YDraig** [comment]
I’m still experiencing this bug on iPhone SE 2020 model (probably the smaller screen.
Can you change episode counter to “ep” to make it shorter and placed after the star rating?
![E74895AB-2A3B-430B-9E00-1168C3F09A17](https://user-images.githubusercontent.com/1481748/152626193-2bdbdafc-c1f9-4ce6-81f2-a900c61f70ad.jpeg)
