### ISSUE TITLE
Voice actors roles bugged on iOS

### ISSUE THREAD

**Issue by Dominic890x** [croberts22/myanilist-bugs#16]
On the MyAniList app for the iPhone, the voice actors roles are messed up. It does not show all the roles the actors has performed UNLESS I search for that specific character they have voiced. It has been like this for a couple months now and it’s very irritating. The website seems to work fine, I’ve only noticed it through the app

## How can you reproduce it?

1. Go to any voice actor
2. Tap on their profile
3. Scroll down to their roles
4. See they do not have all their acting roles

## What's the expected behavior?
 I expect the actors to have every role they have performed, whether it be on my list or not.

## Device Information

iOS Version: 15.1.1

MyAniList Version: 2.10 

iOS Device: iPhone 13 Pro

Jailbroken: no

**Comment by croberts22** [comment]
This will be fixed in version 2.10.2! 🎉

**Comment by croberts22** [comment]
Published in 2.10.2! 🎉
