### ISSUE TITLE
Completing a manga doesn't update chapter/volume count on the server

### ISSUE THREAD

**Issue by seanblue** [croberts22/myanilist-bugs#21]
I completed the manga Hitori Bocchi no Maru Maru Seikatsu today using the app. I had it at 100/101 chapters and 7/8 volumes. Rather than swiping to get it to 101, I opened the edit popup to edit it directly. I set the finish date first, and then set the status to completed. When I set it to completed, the chapter count and volume count automatically updated to 101 and 8 respectively. However, afterwards I went to the website and saw they were still at 100 and 7. So for some reason it updated in the app, but not on the server. Also, since I updated the finish date before setting the status to completed, it's possible that if I had set the status first the same issue would have occurred with finish date (but of course I don't know for sure). It's also possible the same thing happens with anime, but I'm not close enough to finishing any anime to check.

I sent an email with debug logs in case that helps.

**Comment by croberts22** [comment]
Thanks for the logs, those were really helpful! I've found the problem and will have a fix in 2.10.2 👍

**Comment by croberts22** [comment]
Published in 2.10.2! 🎉
