### ISSUE TITLE
Changing from completed to rewatching on Edit page doesn't change AniList.co database

### ISSUE THREAD

**Issue by erictbar** [croberts22/myanilist-bugs#23]
## Describe the issue
While using the edit feature on a completed anime, and marking it as rewatching, opening the page on AniList.co does nothing. Upon refreshing the app, reverts to Completed there as well

## How can you reproduce it?

1. Go to a completed anime on my list such as Vinland Saga
2. Tap on the "..." button and tap Edit
3. Tap on status, and change from Completed to Rewatching
4. Note that the page shows "REWATCHING   24 /24 EP    9 / 10"
5. Tap on the "..." button and tap "View on AniList.co"
6. Note that show is marked as completed
7. Tap on \/ button under thumbnail and Open List Editor
8. Note that the show is marked as Completed with 24 episode progress

## What's the expected behavior?

Marking a show as rewatching should revert the episode count to 0 (after a warning) and add 1 to total rewatches, and update AniList.co
This behavior happens when setting as rewatching from the main show page.

## How reproducible is this issue?
Tested with Vinland Saga on iPhone, Vinland Saga, and Hunter x Hunter (which would end up being a 3rd rewatch) on iPad

## Device Information

iOS Version: (Device 1) iPadOS 15.3 beta (19D5026g)
iOS Version (Device 2) iOS 15.2

MyAniList Version: (Both devices) 2.10.1 (67aada1b) beta

iOS Device: (Device 1) iPad Pro 10.5"
iOS Device (Device 2) iPhone 13 mini

Jailbroken: No

### Screenshots

[https://imgur.com/a/BazgKYw](url)

**Comment by croberts22** [comment]
This should be fixed as a result of https://github.com/croberts22/myanilist-bugs/issues/21.

**Comment by croberts22** [comment]
Published in 2.10.2! 🎉
