### ISSUE TITLE
iPad very sluggish when app is checking for updates from AniList.co

### ISSUE THREAD

**Issue by erictbar** [croberts22/myanilist-bugs#24]
## Describe the issue
When opening app for first time in awhile on my iPad, or any time that I refresh the page to check for updates, page is very sluggish. 

## How can you reproduce it?

1. Open app after not using for a couple days, OR pull to refresh the page
2. Note that "Checking for updates from AniList.co" appears
3. Note that page is sluggish, can be moved a little bit but stalls and is barely able to move. When it does move, it skips a bit

## What's the expected behavior?
Either performance needs to be improved or a loading screen should blanket the whole screen (or both)

## How reproducible is this issue?
Every time I use the app on my iPad. Issue does not occur on iPhone 13 mini

## Device Information

iOS Version: iPadOS 15.3 (19D5026g) beta

MyAniList Version: 2.10.1 (67aada1b)

iOS Device: iPad Pro 10.5"

Jailbroken: No

### Video

[https://streamable.com/1piwu7](url)

**Comment by croberts22** [comment]
I do have a few performance improvements coming into this next release (2.10.2). Notably, there were a few things taking up the animation cycle that was causing some of these hitches. 

I'll be publishing a beta sometime this week; would you like to try this out and see if resolves your problem?

**Comment by erictbar** [comment]
Yes, looking forward to trying it out.

**Comment by erictbar** [comment]
Much better now in limited testing. Some minor sluggishness, but significantly better. However, see #32

**Comment by erictbar** [comment]
The issue is occurring again after opening the app to the new TestFlight beta (2c8ab3e8)
I also noticed that when the app started, it asked for Touch ID (which I have enabled) alongside (perhaps before) the update screen.
After dismissing the update screen, I had to press the unlock button a couple of times before it would bring up Touch ID again.
Then my anime list launched, and the lag came back for about 10 seconds, even though the list wasn't being updated.
When refreshing my list, the lag also occurred, and that replicated to the same degree as my original post.

**Comment by croberts22** [comment]
Thanks for the feedback @erictbar! I will try this out on my iPad later this weekend to see if I can reproduce what you're seeing. In the meantime, do you mind sending me some logs so I can take a look at what might be causing the problem internally? You can do this by going into the app, then tapping on Settings -> About -> Contact.

**Comment by erictbar** [comment]
I reinstalled the App Store app and then went back to TestFlight earlier today to attempt to get premium features back, but that did not help with the lag.
Much better tonight after 98922464 was installed automatically.
