### ISSUE TITLE
Anime Count doesn't match with profile

### ISSUE THREAD

**Issue by schufi73** [croberts22/myanilist-bugs#25]
Hello, I wrote on the discord for this problem they told me to write an email. So I have this problem with the anime count and the manga count, they don’t get update on my profile. I tried everything, force update / logout of my profile (with consequence losing the maggiority of my anime added).
If you can help me that would be awesome!

1.  Add an anime/manga
2. Doesn't show up or at least it shows up like 3 weeks later

I should see the anime on my profile count, doesn't show up. **I also sent an email with my application log!**

## Device Information

iOS Version: 15.2

MyAniList Version: 2.10.2

iOS Device: Iphone 11 pro

Jailbroken: not

### Screenshots

![IMG_2589](https://user-images.githubusercontent.com/69652966/147612579-95fc7972-d43d-475d-b9e8-34d1c77d7813.png)
![IMG_2588](https://user-images.githubusercontent.com/69652966/147612585-4051aab6-b921-4485-993e-e738130247fb.png)

**Comment by seanblue** [comment]
I want to add two important pieces of information from the chat in Discord.

> on the website the anime that I added on my phone doesn't show up

> i tried to logout and the login, then lots of the anime that I added dissapear

Based on those two pieces of information, I don't think it's a problem with the stats. Rather, the anime added in the app aren't being added on the website, so the stats still (accurately) reflect what the website knows about.

> I readded them and nothing changed

I was surprised to hear that logging out and back in didn't fix the issue though. Regardless, for some reason it seems like this user's account isn't properly logged in or something like that.

**Comment by schufi73** [comment]
So is there a way to fix it?

**Comment by schufi73** [comment]
Here is also a video of the thing https://user-images.githubusercontent.com/69652966/147615425-361a30b2-1b82-47a2-ad43-e89d9105454d.MOV
