### ISSUE TITLE
Overlapping labels on anime standard view

### ISSUE THREAD

**Issue by YDraig** [croberts22/myanilist-bugs#26]
## Describe the issue

The rating, airing and next episode stats overlap on titles with long names (English)

## How can you reproduce it?

1. Add a long anime name to your list (Eg: Banished from the hero party)

## What's the expected behavior?

Non overlapping display stats

## How reproducible is this issue?

100%
## Device Information

iOS Version: 15.2

MyAniList Version: 2.10.1

iOS Device: iPhone SE/8

Jailbroken: No

### Screenshots

![6E956D12-1FEC-411A-A17F-7A1EA7760D66](https://user-images.githubusercontent.com/1481748/147613779-a89901f3-f294-4761-87a1-e733052c75df.jpeg)

### Additional Context

Appears similar to issue #2

**Comment by croberts22** [comment]
This should be fixed in the next beta (2.10.2) 👍

**Comment by croberts22** [comment]
Published in 2.10.2! 🎉
