### ISSUE TITLE
Mark Watched/Finished from Lock Screen broken

### ISSUE THREAD

**Issue by YDraig** [croberts22/myanilist-bugs#27]
## Describe the issue

Mark Anime as Watched or Finish series on Lock Screen doesn’t update in App progress
(Haven’t checked Ani-List server)
Similarly when Marked as Finished a new notification to rate the series doesn’t pop up, however I think that’s due to the first bug..

## How can you reproduce it?

1. Hard press Lock Screen notification
2. Mark as watched
3. Unlock phone and go into App
4. Check episode count (hasn’t changed, sync doesn’t fix it)

## What's the expected behavior?

Episode watch counter increases when watched or series is marked completed when finished and prompts to rate series.

## How reproducible is this issue?
Seems to be consistent

## Device Information

iOS Version: 15.2

MyAniList Version: 2.10.1

iOS Device: iPhone SE

Jailbroken:No

### Additional Context

I’m not sure if this bug started at IOS 15 or updating App to 2.10.x as I updated both at the same time.

**Comment by Cazcy** [comment]
Same issue I’m having

**Comment by croberts22** [comment]
Published in 2.10.2! 🎉
