### ISSUE TITLE
Notifications in advance on Lock Screen

### ISSUE THREAD

**Issue by YDraig** [croberts22/myanilist-bugs#29]
## Describe the issue

Lock Screen notification says episode is now airing but it’s not airing for another week when you look in the app

## How can you reproduce it?

1. Add show to “Planning”
2. Notification pops up 1 week before real time
3. Click notification to see real time in app

## What's the expected behavior?

Notification alerts at the correct time

## How reproducible is this issue?

Seems consistent for shows with 0 episodes watched
I thought it was a Timezone issue at first but doesn’t appear to be the case.

## Device Information

iOS Version: 15.2

MyAniList Version: 2.10.1

iOS Device: iPhone SE

Jailbroken: No

### Screenshots

![161D1DB6-22F8-4A07-81D0-0E456A5F5BB6](https://user-images.githubusercontent.com/1481748/148016277-9689f51d-4cbe-42e5-afdc-35d4d3c302ea.jpeg)
![CF9776D2-999A-4D6B-89C1-30B13253FD28](https://user-images.githubusercontent.com/1481748/148016289-cee49db0-8725-40ce-a60a-a47c52f1b021.jpeg)

### Additional Context

Not sure if it’s IOS 15 or latest Anilist that broke it. Updated both at the same time

**Comment by croberts22** [comment]
Thanks for submitting this! 🙂 As this is similar to https://github.com/croberts22/myanilist-bugs/issues/27, I will be closing this one out. It's currently in investigation.
