### ISSUE TITLE
Last list update time in settings isn't shown after app restarts

### ISSUE THREAD

**Issue by seanblue** [croberts22/myanilist-bugs#33]
In settings, the last time the anime and manga lists were updated is supposed to be shown. However, this information doesn't persist (at least visually) when the app restarts. There's no reason the update time should ever be blank, as long as the lists have been downloaded at least one time. 

Steps to reproduce:
1. Open the app and pull down to refresh the anime and manga lists. 
2. Go to general settings to see the update times. 
3. Force kill the app
4. Reopen the app and go back to general settings.

Ideally, at this point the prior update times should still be shown. Instead a hyphen is shown.

![image](https://user-images.githubusercontent.com/5884067/149609623-0e9dc4ac-a653-4b5e-80a7-30f684a5119c.jpeg)

This isn't a new issue, but I figure it's still worth reporting.

**Comment by croberts22** [comment]
Published in 2.10.2! 🎉
