### ISSUE TITLE
All future anime show the airing icon

### ISSUE THREAD

**Issue by seanblue** [croberts22/myanilist-bugs#34]
The green icon that shows up for currently airing anime is now also showing up for all future anime, both in 2022 and beyond. I don't know if this is an issue with the latest beta or if it's another issue from the recent API changes. 

![image](https://user-images.githubusercontent.com/5884067/149647550-4ce29b3b-58e7-4db9-aa1f-896c3d9e7fec.jpeg)

**Comment by croberts22** [comment]
Ah yeah, this was a regression on my part. There was an odd bug with how some icons were colored when they did have airing schedules but were not presently airing (i.e. soon-to-be airing). Fix coming in an upcoming beta 👍

**Comment by croberts22** [comment]
Published in 2.10.2! 🎉
