### ISSUE TITLE
Restoring full version (Tokubetsu) not working

### ISSUE THREAD

**Issue by Dokixi** [croberts22/myanilist-bugs#37]
## Describe the issue

I am not able to restore the full version (Tokubetsu) properly. After I have clicked "restore", I get the message "Purchase Restored!". So everything seems fine from here, but if I now force close the app, then open it again, the app is suddenly back to NOT being unlocked/restored.
## How can you reproduce it?

1. Open 'MyAniList'
2. Go to 'Settings'
2. Tap on 'Unlock MyAniListTokubetsu'
3. Force close the app
4. Open 'MyAniList' again
5. Go to 'Settings'
6. App is now back to NOT being unlocked again

## What's the expected behavior?

After clicking the 'Restore' button in settings and getting the message 'Purchase Restored!', I expected all of the premium features to be unlocked indefinitely.
## How reproducible is this issue?

The issue is easily reproducible every time for me. Even after uninstalling and installing 'MyAniList' again from the App Store.
## Device Information

iOS Version: iPadOS 15.2.1 (19C63)

MyAniList Version: 2.10.1 (67aada1b)

iOS Device: iPad Pro 9.7" (A1673)

Jailbroken: No

### Video

https://youtu.be/KlMmCREGbMo
### Additional Context

This issue/bug was also present on iPadOS 15.2 and with MyAniList Version 2.10.1

**Comment by croberts22** [comment]
This will be available in 2.10.3 🎉
