### ISSUE TITLE
Unable to properly update details about a manga from its description page

### ISSUE THREAD

**Issue by AshenPaladin** [croberts22/myanilist-bugs#57]
## Describe the issue
Attempting to update any details of a manga series from its description page (number of read chapters, status, rating) does not work.

## How can you reproduce it?

1. Go to your manga list
2. Tap on any manga
3. Tap on the chapter button
4. Select a number of read chapters from the picker
5. Tap on the "Update" button
## What's the expected behavior?
Normally, the page should simply update with the new read chapter number.

## How reproducible is this issue?
I can reproduce it every time I try to update a new manga this way, but sometimes there are some additional issues.

## Device Information

iOS Version: 15.4.1

MyAniList Version: 2.12.0 "Komi" (bfeeb6c0a) Beta

iOS Device: iPhone 13 Pro Max

Jailbroken: No

### Screenshots

![IMG_0143](https://user-images.githubusercontent.com/64322403/166098782-acc11b3f-d890-4112-addc-00d99496faa5.PNG)
![IMG_0144](https://user-images.githubusercontent.com/64322403/166098789-fed2b0e6-c1c0-465b-90b7-4ec8d9044bf4.JPEG)

### Video

https://streamable.com/yc1jj0
### Additional Context
Sometimes, attempting to refresh the manga description page immediately after the failed update does nothing (the number of read chapters stays the same), otherwise it gets blocked and fails to load completely as it can be seen in that video. Other times I've had the app crash on me after trying to refresh.

If the app is no longer able to reload that specific manga page usually closing it and opening it back fixes it (although, the number of read chapters is still not updated), but one time I had to go to AniList's website and manually change the number of read chapters there for it to work again (the app had somehow changed my reading chapters to 0 on the website).

**Comment by croberts22** [comment]
@AshenPaladin thanks so much for the detailed report! I've isolated the issue and will have a fix in the upcoming beta. For curiosity's sake, the reason this was not working was because it was assuming that there were no changes being made if _both_ the chapter and volume values were not being updated. I had updated this code recently and messed up the logic here.
