### ISSUE TITLE
Search incorrectly keeps its own section collapse state

### ISSUE THREAD

**Issue by seanblue** [croberts22/myanilist-bugs#58]
Possibly related to changes made for #55. 

As of the current beta, tapping the search bar on the Anime tab (presumably the Manga tab too) may auto-expand all of the sections. I found this odd, so I closed them (seeming to show that #55 was fixed). The problem is, when I then typed something into the search bar, the result was behind a collapsed section. It used to auto-expand the section(s) that had search results. What seems to be happening is that the expand/collapse state is saved separately for when the search box is selected and for when it's not. I find this really confusing. Ideally, this should be the behavior:
* Tapping the search bar (no text yet) automatically closes all expanded sections. Or else, it changes no collapse state from whatever it was before tapping the search bar. Either would be acceptable. 
* Typing in something to search automatically expands the section(s) with results (same as old behavior)
* Can still manually expand/collapse sections (what originally didn't work before #55) since sometimes there are a lot of results and it helps to be able to collapse the sections. 
* When the search box is deselected, I'm not sure what the best behavior is. Maybe keep whatever was already expanded from when the search was done. Maybe just collapse everything. I don't remember what the old behavior was, but maybe it makes sense to go back to that.

**Comment by croberts22** [comment]
Thanks for the feedback here @seanblue! This is a regression that was caused from some of the improvements I was making here with updates. I think what you mentioned is pretty much what the previous behavior was. There are effectively two states that I'm keeping track of (your actual display preferences versus the preferences shown in search), and I think it makes sense to default to showing your display preferences up until you start typing something. From there on, it will auto-expand any section that has series that match the search query.
