### ISSUE TITLE
When i search for a nsfw show in the search bar i can’t find it even though I’ve enabled it from the web browser, this only happened after the censoring update. I am on ios 16 and using an iphone 12

### ISSUE THREAD

**Issue by Ayoubna** [croberts22/myanilist-bugs#67]
## How can you reproduce it?

2. Tap on '...'
3. Scroll down to '...'
4. See error/crash

## Device Information

iOS Version:

MyAniList Version:

iOS Device:

Jailbroken:

**Comment by croberts22** [comment]
Without knowing much context since the form is empty, have you checked your settings in the app to make sure this is enabled? You can view this in Settings > Appearance > Filters.

**Comment by Ayoubna** [comment]
It worked i didn’t notice these settings thank you very much.On 9 Aug 2022, at 8:43 PM, Corey Roberts ***@***.***> wrote:﻿
Without knowing much context since the form is empty, have you checked your settings in the app to make sure this is enabled? You can view this in Settings > Appearance > Filters.
