### ISSUE TITLE
Beta: Profile image and banner doesn't render

### ISSUE THREAD

**Issue by seanblue** [croberts22/myanilist-bugs#97]
## Describe the issue
Sometimes when loading a user from the activity feed, their banner appears briefly and then disappears. It's possible this is only happening the first time, but this is only based on 5 minutes of testing. However, my personal profile picture and banner is not appearing at all.

## How can you reproduce it?
Steps to reproduce the behavior (other user):
1. Go to Feed tab
2. Select user
3. Notice that the banner appears briefly and then disappears

Steps to reproduce the behavior (personal profile):
1. Go to Profile tab
3. Notice that the profile picture and banner do not render. It's possible this is only for my user or that the Profile tab is broken for everyone.

## What's the expected behavior?
Profile picture and banner should always render.

## How reproducible is this issue?
For the Feed issue, it's inconsistent. Might only be the first time a given user is loaded from the Feed.
For the Profile issue, I'm yet to see my profile picture and banner render.

## Device Information

iOS Version: 16.5.1

MyAniList Version: 3.1.0 beta

iOS Device: iPhone 13 Mini

**Comment by croberts22** [comment]
This is a known issue and will be fixed in the next beta! 👍
